server:
  port: 8081

spring:
  application:
    name: beacon-ingest
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${beacon.kafka.group-id:beacon-ingest}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: dev.xj16.beacon.common.LogEvent
        spring.json.trusted.packages: "dev.xj16.beacon.common"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

beacon:
  kafka:
    topic: ${BEACON_TOPIC:beacon.events}
    group-id: beacon-ingest
    partitions: 3
  elasticsearch:
    uri: ${ELASTICSEARCH_URI:http://localhost:9200}
    index: beacon-events

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
