-- Beacon alerting metadata schema.
--
-- This runs against the default zero-infrastructure H2 database so the alerting engine is fully
-- functional with no external services. When SPRING_DATASOURCE_URL points at the compose Postgres,
-- Postgres has already been initialised by docker/postgres-init.sql (which defines the same tables),
-- and these IF NOT EXISTS statements are harmless no-ops.

CREATE TABLE IF NOT EXISTS service_catalog (
    name         VARCHAR(255) PRIMARY KEY,
    team         VARCHAR(255),
    environment  VARCHAR(64) NOT NULL DEFAULT 'unknown',
    created_at   TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alert_rule (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service            VARCHAR(255),
    min_anomaly_score  DOUBLE PRECISION NOT NULL DEFAULT 0.8,
    min_severity       INT NOT NULL DEFAULT 4,
    channel            VARCHAR(64) NOT NULL DEFAULT 'slack',
    enabled            BOOLEAN NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alert (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       VARCHAR(255) NOT NULL,
    service        VARCHAR(255),
    team           VARCHAR(255),
    severity       INT NOT NULL,
    anomaly_score  DOUBLE PRECISION NOT NULL,
    channel        VARCHAR(64) NOT NULL,
    message        VARCHAR(2048),
    notified       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_alert_created_at ON alert (created_at);
CREATE INDEX IF NOT EXISTS idx_alert_event_id ON alert (event_id);
